[project]
name = "MMI_put_what_where"
authors = [{name = "Tobias Verheijen"}, {name = "Mathias Øgaard"}]
version = "1.1.0"
dependencies = [
    "numpy",
    "pygame",
    "pyaudio",
    "SpeechRecognition",
    "dlib"
]
requires-python = ">=3.10"
